### ISSUE TITLE
1.0 Warnings in log window

### ISSUE THREAD

**Issue by dimitrov-adrian** [nmaier/simpleDLNA#11]
Playing is working (mp4 file, h264, AAC)
But get warnings.

![untitled](https://cloud.githubusercontent.com/assets/1009639/4774403/0915aa52-5bad-11e4-8b9c-03becfcf2e16.png)

**Comment by VikPC** [comment]
Sony Bravia 32W705B
Windows 7 64bit
all tested files streams OK
But 

i see same errors (in picture dimitrov-adrian) + each time i start/stop server or reboot PC.. TV add new tab with server name to tv media player... like i have another runned SimpleDLNA

Full log..
=============================
2015-02-18 02:25:51,079 NOTICE [  1] HttpServer                     - Running HTTP Server: WIN64/6.1 UPnP/1.0 DLNADOC/1.5 sdlna/1.0 on port 51752
2015-02-18 02:25:51,157 NOTICE [  1] SsdpHandler                    - SSDP service started
2015-02-18 02:25:52,280   INFO [  6] FileStore                      - FileStore at C:\Users\User\AppData\Local\SimpleDLNA\sdlna.cache is ready
2015-02-18 02:25:53,075   INFO [ 10] FFmpeg                         - Found ffmpeg.exe at C:\Program Files (x86)\Nils Maier\ffmpeg\bin\ffmpeg.exe
2015-02-18 02:25:53,247 NOTICE [  6] HttpServer                     - New mount at: http://192.168.1.2:51752/mm-1/description.xml
2015-02-18 02:25:53,247 NOTICE [  6] State                          - My Movies loaded in 1,83 seconds
2015-02-18 02:25:54,760   INFO [ 12] HttpClient                     - 192.168.1.6:59547 - 200 response for /mm-1/description.xml
2015-02-18 02:25:54,760   INFO [ 11] HttpClient                     - 192.168.1.6:59548 - 200 response for /mm-1/description.xml
2015-02-18 02:25:54,760   INFO [ 14] HttpClient                     - 192.168.1.165:35349 - 200 response for /mm-1/description.xml
2015-02-18 02:25:54,776   INFO [ 13] HttpClient                     - 192.168.1.6:59549 - 200 response for /mm-1/contentDirectory.xml
2015-02-18 02:25:54,776   INFO [ 13] HttpClient                     - 192.168.1.165:35350 - 200 response for /mm-1/contentDirectory.xml
2015-02-18 02:25:54,776   INFO [ 13] HttpClient                     - 192.168.1.6:59551 - 200 response for /mm-1/connectionManager.xml
2015-02-18 02:25:54,776   INFO [ 14] HttpClient                     - 192.168.1.6:59550 - 200 response for /mm-1/contentDirectory.xml
2015-02-18 02:25:54,807   INFO [ 14] HttpClient                     - 192.168.1.6:59552 - 200 response for /mm-1/MSMediaReceiverRegistrar.xml
2015-02-18 02:25:54,823   INFO [ 14] HttpClient                     - 192.168.1.165:35351 - 200 response for /mm-1/connectionManager.xml
2015-02-18 02:25:54,823   INFO [ 13] HttpClient                     - 192.168.1.6:59553 - 200 response for /mm-1/connectionManager.xml
2015-02-18 02:25:54,854   INFO [ 14] HttpClient                     - 192.168.1.6:59555 - 200 response for /mm-1/description.xml
2015-02-18 02:25:54,854   INFO [ 14] HttpClient                     - 192.168.1.6:59556 - 200 response for /mm-1/contentDirectory.xml
2015-02-18 02:25:54,869   INFO [ 14] HttpClient                     - 192.168.1.6:59557 - 200 response for /mm-1/connectionManager.xml
2015-02-18 02:25:54,869   INFO [ 14] HttpClient                     - 192.168.1.6:59558 - 200 response for /mm-1/MSMediaReceiverRegistrar.xml
2015-02-18 02:25:55,057   INFO [ 13] HttpClient                     - 192.168.1.6:59554 - 200 response for /mm-1/control
2015-02-18 02:25:55,057   INFO [ 14] HttpClient                     - 192.168.1.165:35352 - 200 response for /mm-1/control
2015-02-18 02:25:55,088   INFO [ 13] HttpClient                     - 192.168.1.6:59560 - 200 response for /mm-1/description.xml
2015-02-18 02:25:55,088   INFO [ 13] HttpClient                     - 192.168.1.6:59561 - 200 response for /mm-1/contentDirectory.xml
2015-02-18 02:25:55,088   INFO [ 13] HttpClient                     - 192.168.1.6:59562 - 200 response for /mm-1/connectionManager.xml
2015-02-18 02:25:55,103   INFO [ 13] HttpClient                     - 192.168.1.6:59563 - 200 response for /mm-1/MSMediaReceiverRegistrar.xml
2015-02-18 02:25:55,275   INFO [ 14] HttpClient                     - 192.168.1.6:59559 - 200 response for /mm-1/control
2015-02-18 02:25:55,291   INFO [ 13] HttpClient                     - 192.168.1.165:35353 - 200 response for /mm-1/control
2015-02-18 02:25:55,478   INFO [ 13] HttpClient                     - 192.168.1.6:59564 - 200 response for /mm-1/control
2015-02-18 02:25:55,493   INFO [ 13] HttpClient                     - 192.168.1.165:35354 - 200 response for /mm-1/control
2015-02-18 02:25:55,509   INFO [ 14] HttpClient                     - 192.168.1.6:59565 - 200 response for /mm-1/description.xml
2015-02-18 02:25:55,525   INFO [ 13] HttpClient                     - 192.168.1.6:59566 - 200 response for /mm-1/contentDirectory.xml
2015-02-18 02:25:55,525   INFO [ 14] HttpClient                     - 192.168.1.6:59567 - 200 response for /mm-1/connectionManager.xml
2015-02-18 02:25:55,556   INFO [ 13] HttpClient                     - 192.168.1.6:59569 - 200 response for /icon/largePNG
2015-02-18 02:25:55,743   INFO [ 14] HttpClient                     - 192.168.1.6:59568 - 200 response for /mm-1/control
2015-02-18 02:25:55,961   INFO [ 14] HttpClient                     - 192.168.1.6:59570 - 200 response for /mm-1/control
2015-02-18 02:25:56,180   INFO [ 14] HttpClient                     - 192.168.1.6:59571 - 200 response for /mm-1/control
2015-02-18 02:25:58,099   INFO [ 14] HttpClient                     - 192.168.1.6:59572 - 200 response for /mm-1/control
2015-02-18 02:25:58,301   INFO [ 14] HttpClient                     - 192.168.1.6:59573 - 200 response for /mm-1/control
2015-02-18 02:26:07,880   INFO [  9] HttpServer                     - Unregistered Media Server 6e6c6473-6661-2173-2043-4f4d504c455e
2015-02-18 02:26:10,984  ERROR [ 10] FileStore                      - Failed to serialize an object of type NMaier.SimpleDlna.FileMediaServer.VideoFile
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SQLiteCommand'.
   at System.Data.SQLite.SQLiteCommand.CheckDisposed()
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at NMaier.SimpleDlna.FileMediaServer.FileStore.MaybeStoreFile(BaseFile file)
2015-02-18 02:26:11,031  ERROR [ 10] VideoFile                      - Failed to look up subtitle
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SQLiteCommand'.
   at System.Data.SQLite.SQLiteCommand.CheckDisposed()
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at NMaier.SimpleDlna.FileMediaServer.FileStore.MaybeStoreFile(BaseFile file)
   at NMaier.SimpleDlna.FileMediaServer.VideoFile.get_Subtitle()
2015-02-18 02:26:21,046  ERROR [ 10] FileStore                      - Failed to serialize an object of type NMaier.SimpleDlna.FileMediaServer.VideoFile
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SQLiteCommand'.
   at System.Data.SQLite.SQLiteCommand.CheckDisposed()
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at NMaier.SimpleDlna.FileMediaServer.FileStore.MaybeStoreFile(BaseFile file)
2015-02-18 02:26:21,046  ERROR [ 10] VideoFile                      - Failed to look up subtitle
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SQLiteCommand'.
   at System.Data.SQLite.SQLiteCommand.CheckDisposed()
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at NMaier.SimpleDlna.FileMediaServer.FileStore.MaybeStoreFile(BaseFile file)
   at NMaier.SimpleDlna.FileMediaServer.VideoFile.get_Subtitle()
2015-02-18 02:26:31,061  ERROR [ 10] FileStore                      - Failed to serialize an object of type NMaier.SimpleDlna.FileMediaServer.VideoFile
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SQLiteCommand'.
   at System.Data.SQLite.SQLiteCommand.CheckDisposed()
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at NMaier.SimpleDlna.FileMediaServer.FileStore.MaybeStoreFile(BaseFile file)
2015-02-18 02:26:31,061  ERROR [ 10] VideoFile                      - Failed to look up subtitle
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SQLiteCommand'.
   at System.Data.SQLite.SQLiteCommand.CheckDisposed()
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at NMaier.SimpleDlna.FileMediaServer.FileStore.MaybeStoreFile(BaseFile file)
   at NMaier.SimpleDlna.FileMediaServer.VideoFile.get_Subtitle()
2015-02-18 02:26:41,076  ERROR [ 10] FileStore                      - Failed to serialize an object of type NMaier.SimpleDlna.FileMediaServer.VideoFile
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SQLiteCommand'.
   at System.Data.SQLite.SQL

**Comment by nmaier** [comment]
Yeah, seems like the background cacher tries to insert things into the cache DB after the DB itself was already shut down. Besides these pesky warning, this shouldn't have any effect, tho.
Still, I'll look into it and fix it when I get some time.

**Comment by nmaier** [comment]
PS: That was targeted at @VikPC of course. @VikPC in the future, please do not hijack other people's issues, but instead file a new one.

**Comment by daf0x** [comment]
I think that this problem is caused by the GUI's Config.cache setting. This setting is supposed to store a folder name, but in FormMain's constructor it is treated like a filename (line 94). This eventually causes FileServer to open a FileStore with a folder rather than a file, which will fail.
