### ISSUE TITLE
Error Message In Log

### ISSUE THREAD

**Issue by nnthnn** [nmaier/simpleDLNA#3]
Great project by the way!

When I start a server with SimpleDLNA.exe I see a bunch of reoccuring errors in the log. Everything appears to work fine though and I can still browse the folders from my DLNA client. I am not sure if the port binding error is causing some other problem, but I thought I would at least report it.

```
2013-12-23 10:31:24,261  DEBUG [  1] HttpServer     - Registered Handler for /icon/
2013-12-23 10:31:24,305   INFO [  1] HttpServer     - Running HTTP Server: WIN64/6.2 UPnP/1.0 DLNADOC/1.5 sdlna/0.13 on port 53015
2013-12-23 10:31:24,313   INFO [  1] SsdpHandler    - SSDP service started
2013-12-23 10:31:41,197   INFO [  6] FileStore      - FileStore at C:\Users\Nathan\AppData\Local\Temp\sdlna.cache is ready
2013-12-23 10:31:41,397  DEBUG [ 10] Thumbnailer    - thumber started
2013-12-23 10:31:41,406  DEBUG [  6] HttpServer     - Registered Handler for /mm-1/
2013-12-23 10:31:41,439  DEBUG [  6] SsdpHandler    - NotifyAll
2013-12-23 10:31:41,444  DEBUG [  6] SsdpHandler    - NotifyDevice
2013-12-23 10:31:41,471  ERROR [  6] Datagram       - System.Net.Sockets.SocketException (0x80004005): The requested address is not valid in its context
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at NMaier.SimpleDlna.Server.Ssdp.Datagram.Send()
2013-12-23 10:31:41,473  ERROR [  6] Datagram       - System.Net.Sockets.SocketException (0x80004005): The requested address is not valid in its context
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at NMaier.SimpleDlna.Server.Ssdp.Datagram.Send()
2013-12-23 10:31:41,474  ERROR [  6] Datagram       - System.Net.Sockets.SocketException (0x80004005): The requested address is not valid in its context
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at NMaier.SimpleDlna.Server.Ssdp.Datagram.Send()
```

**Comment by nyuszika7h** [comment]
I have the same issue. I had to disable the VirtualBox Host-Only and Ethernet adapters to get it to work.
